### ISSUE TITLE
INCREMENTAR SCRIPT "ABERTURA DE CHAMADOS" PARA 60 PASSOS 

### ISSUE THREAD

**Issue by enayzuin** [johnenderson/IssueTrackerPro#4]
INCREMENTAR SCRIPT "ABERTURA DE CHAMADOS" PARA 60 PASSOS :

Utilizar a visão ciclica para controlar melhor os fluxos da abertura de chamado.

**Comment by johnenderson** [comment]
1.	1 Criar nova pasta na área de trabalho;
2.	2 Coletar evidencia 1: Não é possível realizar conexão a partir do navegador Google Chrome;
3.	3 Tirar Print do navegador Google Chrome;
4.	4 Salvar o Print na pasta anteriormente criada na Area de Trabalho;
5.	5 Coletar evidencia 2: Abrir CMD;
6.	6 Digitar o comando para testar conexão com algum Website da Internet. Ex. PING UOL.COM.BR;
7.	7 Executar o Print do retorno da console;
8.	8 Salvar o Print na pasta anteriormente criada na area de trabalho;
9.	Abrir navegador;
10.	Acessar URL do sistema de Chamados da empresa;
11.	Digitar Usuário;
12.	Digitar Senha;
13.	Realizar Login;
14.	Ir até o menu para instanciação de chamados;
15.	Instanciar o Workflow de Chamados;
16.	Gerar número do chamado aleatoriamente
17.	EXIBIR MENSAGEM de "BOAS VINDAS";	System.out.println("Seja bem vindo ao sistema de chamados, insira seu nome para iniciar:");
18.	EXIBIR MENSAGEM de "VAMOS COMEÇAR" com o nome do INICIADOR: System.out.println("Certo " + chamado.getIniciadorChamado() + " vamos começar!");
19.	EXIBIR MENSAGEM: "Você é o solicitante do chamado? (Digite 1 para 'SIM' ou 2 para 'NÃO'";
20.	SE SIM, REGISTRAR quem é o SOLICITANTE;
21.	SE NÃO, definir que o INICIADOR é o proprio SOLICITANTE;
22.	EXIBIR MENSAGEM: "Informar Telefone ou Ramal para contato:";
23.	REGISTRAR: Telefone ou ramal para contato;
24.	EXIBIR MENSAGEM: "Informar o tipo de Localização "1. Loja, 2. Fabrica ou 3. Escritório");
25.	REGISTRAR: O codigo do "TIPO DE LOCALIZAÇÃO";
26.	EXIBIR MENSAGEM: "Informe qual é a "AREA DO SOLICITANTE DO CHAMADO";
27.	REGISTRAR: Nome da AREA DO SOLICITANTE DO SOLICITANTE chamado;
28.	EXIBIR MENSAGEM: Ex.: "Digite o e-mail do Solicitante do chamado:"
29.	REGISTRAR: E-amil do solicitante;
30.	EXIBIR MENSAGEM: "Deseja informar mais E-mails? Digite '1' para 'SIM' e '2' para 'NÃO'"
31.	SE SIM, apresentar mensagem "Informar e-mails adicionais a serem notificados, separados por ';'. (Ex: e-mail1@teste.com; email2@teste.com)")"
32.	Incluir registro no campo: E-mails adicionais a serem notificados, separados por ";". (Ex: e-mail1@teste.com; email2@teste.com) EMAILS_TO_BE_NOTIFIED
33.	SE NÃO, prosseguir com o programa
34.	EXIBIR MENSAGEM: "Informe qual é o Título para este chamado:";
35.	REGISTRAR: "TÍTULO" do chamado
36.	EXIBIR MENSAGEM: "Informe qual é o Tipo do Chamado: ";
37.	REGISTRAR: TIPO DE CHAMADO (Segurança da informação, Infraestrutura, Sistemas);
38.	EXIBIR MENSAGEM: Selecionar opções: Gravidade (0. Erro que impede a continuidade do projeto de implantação, 1. Sistema Indisponível, 2. Erro critico para operação do sistema, 3. Erro médio ou de menor impacto, 4. Dúvidas e ou melhorias).
39.	REGISTRAR: Gravidade;
40.	EXIBIR MENSAGEM: Selecionar opções: Urgência (1. Necessário ação imediata "Usar apenas na gravidade 1", 2. Atender o mais cedo possível, 3. Prazo padrão de atendimento);
41.	REGISTRAR: Urgência;
42.	EXIBIR MENSAGEM: Qual a sua dúvida ou problema? (Se for um problema, detalhe o máximo possível incluindo como anexo a tela do erro)
43.	REGISTRAR: descrição do chamado
44.	Incluir Evidencia de número 1 anexo ao chamado;
45.	Incluir Evidencia de número 2 anexo ao chamado;
46.	EXIBIR MENSAGEM: “Tem certeza que deseja encerrar o chamado?”
47.	REGISTRAR ESCOLHA anterior;
48.	REGISTRAR CHAMADO;
49.	EXIBIR RESUMO DO CHAMADO.
