### ISSUE TITLE
Utilizar orientação a objetos

### ISSUE THREAD

**Issue by enayzuin** [johnenderson/IssueTrackerPro#8]
Na classe principal "NewTicket" todas as ações são feitas de maneira centralizada. Separar as responsabilidades de acordo com os padrões de orientação a objetos.

**Comment by johnenderson** [comment]
https://www.instagram.com/p/CkO5m7EO7r3/?utm_source=ig_web_copy_link
https://www.instagram.com/p/CjjDM2VAvGC/?utm_source=ig_web_copy_link

**Comment by enayzuin** [comment]
Utilizar o https://app.diagrams.net/ para organizar a estrutura de objetos e como eles vão se relacionar
